---
# handlers file for consul

- name: restart consul
  service:
    name: "{{ consul_service_name }}"
    state: restarted
  when: consul_service_manage
  tags: consul

- name: reload consul
  service:
    name: "{{ consul_service_name }}"
    state: reloaded
  tags: consul

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
